### ISSUE TITLE
Testdata for Lenet-5

### ISSUE THREAD

**Issue by xldeng-chn** [zs5978/Register-config-in-NVDLA-for-LeNet-5#1]
Does author has testdata in NVDLA format for Lenet-5?

**Comment by zs5978** [comment]
You can contact me by QQ 597829858




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zs5978/Register-config-in-NVDLA-for-LeNet-5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 晚上8:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zs5978/Register-config-in-NVDLA-for-LeNet-5] Testdata for Lenet-5 (#1)





 
Does author has testdata in NVDLA format for Lenet-5?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
